version: 0.2

phases:
  install:
    commands:
      - pip3 install -q awscli --upgrade --user
      - yum -q install -y jq
  pre_build:
    commands:
      ### Login to Amazon ECR
      - echo Logging in to Amazon ECR...
      - SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id $SECRET_NAME --query SecretString --output text)
      - aws ecr get-login-password --region $AWS_REGION --registry-ids $SECRET_VALUE | docker login --username AWS --password-stdin
#      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      ### Pulling the image
      - echo Pulling latest image from Docker Hub
      - docker pull $AWS_ECR_REPO:$IMAGE_TAG
      ### Creating the ECR repository
      - aws ecr describe-repositories --repository-names ${AWS_ECR_REPO} || aws ecr create-repository --repository-name ${AWS_ECR_REPO}
  build:
    commands:
      ### Building the image
      - echo Build started on `date`
      - docker tag $AWS_ECR_REPO:$IMAGE_TAG $ECR_REGISTRY/$AWS_ECR_REPO:$IMAGE_TAG
      - echo Build completed on `date`
  post_build:
    commands:
      ### Publish the docker image to ECR
      - echo Pushing the Docker image...
      - docker push $ECR_REGISTRY/$AWS_ECR_REPO:$IMAGE_TAG