#version: 0.2
#name: AWS Code Pipeline Docker Push
#on:
#  push:
#    branches: [ "master" ]
#jobs:
#  AWS-Code-Pipeline-Test:
#    name: Build Docker Image
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Setup AWS ECR Details
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{secrets.AWS_REGION}}
#      - name: Login to Amazon ECR
#        id: login-pf-aws-ecr
#        uses: aws-actions/amazon-ecr-login@v1
#      - name: Build and push the tagged docker image to Amazon ECR
#        env:
#          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
#          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
#          IMAGE_TAG: ${{ github.sha }}  # Use commit SHA for dynamic tagging
#        run: |
#          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_REGION --registry-ids $ECR_REGISTRY)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
