version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - echo "Insert the breakpoint command into your command list"
      - codebuild-breakpoint
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - REPOSITORY_URI=$ECR_REGISTRY/$AWS_ECR_REPO
      - IMAGE_TAG=latest  # Use CODEBUILD_BUILD_ID or 'latest'

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - image_definitions.json  # Optional (for deployments using image definitions)

